#!/bin/sh

set -e

echo "Starting app..."

nohup ollama serve > /dev/null 2> /dev/null &
OLLAMA_PID=$!

while ! nc -z localhost 11434; do
  sleep 0.1  # wait for 1/10 of the second before check again
done


./venv/bin/python $0.py


kill -INT $OLLAMA_PID
wait
